import os

gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for lambdaweb project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
	SECRET_KEY = os.environ.get('SECRET_KEY')
except KeyError as e:
	print('Secret key not found. Error message: {0}'.format(e))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition





ROOT_URLCONF = 'lambdaweb.urls'

WSGI_APPLICATION = 'lambdaweb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases




# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
	os.path.join(BASE_DIR, 'lambdaweb', 'static'),
)
SITE_ID = 1

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS'   : [os.path.join(BASE_DIR, 'lambdaweb', 'templates'), ],
		'OPTIONS': {
			'context_processors': [
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'django.core.context_processors.i18n',
				'django.core.context_processors.debug',
				'django.core.context_processors.request',
				'django.core.context_processors.media',
				'django.core.context_processors.csrf',
				'django.core.context_processors.tz',
				'sekizai.context_processors.sekizai',
				'django.core.context_processors.static',
				'cms.context_processors.cms_settings'
			],
			'loaders'           : [
				'django.template.loaders.filesystem.Loader',
				'django.template.loaders.app_directories.Loader',
				'django.template.loaders.eggs.Loader'
			],
		},
	},
]

MIDDLEWARE_CLASSES = (
	'cms.middleware.utils.ApphookReloadMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'cms.middleware.user.CurrentUserMiddleware',
	'cms.middleware.page.CurrentPageMiddleware',
	'cms.middleware.toolbar.ToolbarMiddleware',
	'cms.middleware.language.LanguageCookieMiddleware'
)

INSTALLED_APPS = (
	'djangocms_admin_style',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.admin',
	'django.contrib.sites',
	'django.contrib.sitemaps',
	'django.contrib.staticfiles',
	'django.contrib.messages',
	'cms',
	'menus',
	'sekizai',
	'treebeard',
	'djangocms_text_ckeditor',
	'filer',
	'easy_thumbnails',
	'djangocms_column',
	'djangocms_link',
	'cmsplugin_filer_file',
	'cmsplugin_filer_folder',
	'cmsplugin_filer_image',
	'cmsplugin_filer_utils',
	'djangocms_style',
	'djangocms_snippet',
	'djangocms_googlemap',
	'djangocms_video',
	'bootstrap3',
	'taggit',
	'lambdaweb',
	'news'
)

LANGUAGES = (
	## Customize this
	('ru', gettext('ru')),
)

CMS_LANGUAGES = {
	## Customize this
	1        : [
		{
			'hide_untranslated'   : False,
			'code'                : 'ru',
			'redirect_on_fallback': True,
			'public'              : True,
			'name'                : gettext('ru'),
		},
	],
	'default': {
		'hide_untranslated'   : False,
		'redirect_on_fallback': True,
		'public'              : True,
	},
}

CMS_TEMPLATES = (
	## Customize this
	# ('page.html', 'Page'),
	# ('feature.html', 'Page with Feature')
	('index.html', gettext('Homepage')),
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DATABASES = {
	'default': {
		'CONN_MAX_AGE': 0,
		'ENGINE'      : 'django.db.backends.sqlite3',
		'HOST'        : 'localhost',
		'NAME'        : 'project.db',
		'PASSWORD'    : '',
		'PORT'        : '',
		'USER'        : ''
	}
}

MIGRATION_MODULES = {

}

THUMBNAIL_PROCESSORS = (
	'easy_thumbnails.processors.colorspace',
	'easy_thumbnails.processors.autocrop',
	'filer.thumbnail_processors.scale_and_crop_with_subject_location',
	'easy_thumbnails.processors.filters'
)
